[package]
name = "well-written-server"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "4.0.14"
async-graphql-axum = "4.0.14"
axum = "0.5.16"
tokio = { version = "1.21.2", features = ["full"] }
